### ISSUE TITLE
Exceptions should not prevent further handlers from being called

### ISSUE THREAD

**Issue by tilgovi** [WebReflection/event-target#2]
See step 2.7 of https://dom.spec.whatwg.org/#concept-event-listener-inner-invoke

Unfortunately, I don't know off the top of my head what the best way to report the exception would be.

- `console.error`
- `window.dispatchEvent('error', new Error(...))
- something else?

**Comment by tilgovi** [comment]
I think it's this:

```js
var event = new ErrorEvent('error', {
  message: e.message,
  filename: e.fileName,
  lineno: e.lineNumber,
  colno: e.columnNumber,
  error: e
});
window.dispatchEvent('error', event);
```

**Comment by WebReflection** [comment]
I don't know how you ended up using this 5 years old piece of software, but if you need it, I strongly suggest you to use DOM4 which is actively maintained.

This repository is a dead-end.

Apologies for that.

**Comment by WebReflection** [comment]
The DOM4 https://github.com/WebReflection/dom4

**Comment by tilgovi** [comment]
I've written a standalone implementation of the EventTarget interface that can be mixed into object prototypes. If you have no intention if improving this project, would you mind if I took the name on npm, with a new major version number? It does not share any code with this project, but I'd welcome your input on it.

**Comment by WebReflection** [comment]
if [storage-mock](https://www.npmjs.com/package/storage-mock) and [weapp-adapter](https://www.npmjs.com/package/weapp-adapter) devs are OK with it, works for me.
