### ISSUE TITLE
Resolve to native EventTarget if found extensible

### ISSUE THREAD

**Issue by medikoo** [WebReflection/event-target#4]
As now both FF and Chrome provide `EventTarget` as normal extensible class, wouldn't it be good to return it by default in those engines?

**Comment by WebReflection** [comment]
that's already the case:
https://github.com/WebReflection/event-target/blob/master/esm/index.js#L5-L7

the EventTarget is tested if it can be used as constructor. If not, it's polyfilled.

**Comment by medikoo** [comment]
Sorry, didn't notice. Great to see that

**Comment by WebReflection** [comment]
this is a polyfll ... the real use case for polyflls is to be used ... as polyfill, so that you can remove the script without bothering dependencies once the time is right.

All you need to really do here is:
```html
<script src="https://unpkg.com/event-target"></script>
```

that's it, modules are there only for convenience.

**Comment by medikoo** [comment]
It's one of hundreds of modules to be used by app. Do you recommend listing hundreds of script elements in main HTML file?

Also I tend to not prepare different script/html per each browser. Therefore it's good to have logic that loads polyfill conditionally directly in a code.

**Comment by WebReflection** [comment]
> Do you recommend listing hundreds of script elements in main HTML file?

I've never used hundreds polyflls, maximum 4 or 5, not a big deal

> it's good to have logic that loads polyfill conditionally directly in a code.

your suggestion doesn't make this polyfill conditional

I am **really** without time for this. This is 100% code covered polyfill for any env. You have options, you can also send PR.

I don't have time for any of these requests, this module is nearly perfect to me already.

**Comment by medikoo** [comment]
> I've never used hundreds polyflls, maximum 4 or 5, not a big deal

I want to use it as ponyfil, so as a regular module and not something that's loaded externally with side effect of changing global environment.

**Comment by WebReflection** [comment]
there are no side effects here because the global is unusable in any other way

feel free to look elsewhere, I'm closing this conversation.

**Comment by WebReflection** [comment]
also:
https://github.com/WebReflection/event-target/blob/master/cjs/index.js#L4-L9

this **is** a pony fill for CommonJS and ESM
