### ISSUE TITLE
CJS & browserify: EventTarget is not a constructor

### ISSUE THREAD

**Issue by Buzut** [WebReflection/event-target#9]
I installed the module via npm, required it as said in the docs (Browserify 16.2.2 handles the bundling).

```const EventTarget = require('event-target').default;```

but I get an error:

```
Safari 11.1 (doesn't have EventTarget constructor)
TypeError: undefined is not a constructor (evaluating 'new EventTarget')

FF 61 (has support, works perfect w/o polyfill)
TypeError: EventTarget is not a constructor
```

Including the script tag from the CDN works though.

**Comment by WebReflection** [comment]
This should be fixed in the new module `@ungap/event-target`
